version: '3'
services:
  myspringapp:
    image: dockerDemo
    build: .
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - mypostgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://mypostgres:5432/mydb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
  mypostgres:
    image: postgres
    restart: always
    ports:
     - "5432:5432"
    environment:
     - POSTGRES_PASSWORD=password
     - POSTGRES_USER=postgres
     - POSTGRES_DB=mydb